/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 04-Jun-2021 17:29:29
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 61
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 61;
const real32_T B[61] = {
  0.0008481356199,0.0002342359949,-0.000885855814,-0.0008538881666,0.0007325511542,
   0.001740405336,-2.724100765e-18,-0.002646756591,-0.001678440487, 0.002887436422,
   0.004269321915, -0.00152894645,-0.007029845845,-0.002151688794,  0.00846835319,
   0.008096252568,-0.006680011749, -0.01502130926,1.107068919e-17,   0.0203067828,
     0.0122449575, -0.02025015838, -0.02918976918,  0.01037021633,  0.04835156351,
     0.0154489046, -0.06612152606, -0.07327753305,  0.07871344686,   0.3064393699,
     0.4163275957,   0.3064393699,  0.07871344686, -0.07327753305, -0.06612152606,
     0.0154489046,  0.04835156351,  0.01037021633, -0.02918976918, -0.02025015838,
     0.0122449575,   0.0203067828,1.107068919e-17, -0.01502130926,-0.006680011749,
   0.008096252568,  0.00846835319,-0.002151688794,-0.007029845845, -0.00152894645,
   0.004269321915, 0.002887436422,-0.001678440487,-0.002646756591,-2.724100765e-18,
   0.001740405336,0.0007325511542,-0.0008538881666,-0.000885855814,0.0002342359949,
  0.0008481356199
};
